###For each of these data files, I was able to click on them and select import data which autogenerated the necessary code in the console below


###Bird Malaria Begins Here 

Bird_Malaria_Data<-read.csv("Bird_Malaria_Data.csv")

View(Bird_Malaria_Data)

summary(Bird_Malaria_Data)

table(Bird_Malaria_Data$Treatment, Bird_Malaria_Data$Response)

counts<-table(Bird_Malaria_Data$Treatment, Bird_Malaria_Data$Response)
percents=100*prop.table(counts,2)
                        
plot(counts, main="Barone, Victoria: Bird Malaria Treatment vs. Response", 
        xlab="Treatment", col=c("pink", "lightyellow"),
        legend=rownames(counts), 
        args.legend = list(x="topleft", horiz=TRUE), beside=FALSE)


